### ISSUE TITLE
部分例子得出的编辑脚本似乎有问题？

### ISSUE THREAD

**Issue by sws797** [skybig233/O_ND_algorithm#1]
https://blog.csdn.net/qq_44506605/article/details/110085478 中给出的例子是 A=`ABCABBA`，b=`CBABAC`，得出的编辑脚本一致。

但用 A=`ABCDE`，b=`ABCF`得出的脚本为
```
[(3, 'S3'), (4, 'S4')]
```

**Comment by sws797** [comment]
好像是 A 末尾多出来的部分全部识别成了`S`

**Comment by skybig233** [comment]
已修复
这个bug是因为AB长度不等时，数组越界导致的
更新V数组保存逻辑，横坐标为-1时表示不可达
对于这个用例，更新后V数组为[[3], [3, 4, 4], [-1, -1, -1, 5, -1]]，输出结果为[(3, 'D'), (4, 'S3')]
